### ISSUE TITLE
Problem with random_state

### ISSUE THREAD

**Issue by augmentedme** [EpistasisLab/ellyn#18]
I really like your project and implementation. I wanted to use ellyn as a Classifier as below:
    **learner = ellyn(classification=True,
                    random_state=101,
                    class_m4gp=True,
                    prto_arch_on=True,
                    selection='lexicase',
                    fit_type='F1' # can be 'F1' or 'F1W' (weighted F1)
                   )**
                   
However, everytime, I am getting different result, so I am getting different y_pred each time. Could you please clarify where am doing it wrong?

**Comment by lacava** [comment]
did you figure it out? could be because of parallelism. first thing I would try is running on a single thread.

**Comment by augmentedme** [comment]
Hi,

Many thanks for coming back to me.

I couldn't figured it out yet. I am running on CPU and didn't set
multi-threading. Would love see the solution with single thread.

Could you please check in your free time and share the findings. You
response would be highly appreciated.

Regards,
Abdullah

**Comment by lacava** [comment]
try passing `islands=False`. multithreading can make the results impossible to reproduce, even with fixed seeds.

**Comment by augmentedme** [comment]
Hi William,

Even after setting the islands=False flag, still getting the random results.

I also made sure I am running on single thread.

"import threading
print(threading.active_count())"

This returns as 1.



Regards,
Abdullah
